"""mensagem_da_migracao

Revision ID: 8c23e31bf924
Revises: aeb195611cd2
Create Date: 2026-05-01 20:56:13.217225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c23e31bf924'
down_revision: Union[str, None] = 'aeb195611cd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contas', sa.Column('data_de_criacao', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contas', 'data_de_criacao')
    # ### end Alembic commands ###
